[project]
name = "freezing-model"
version = "0.9.0"
description = "Freezing model for deployment"
readme = "README.md"
authors = ["Hans Lillelid <hans@

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
