from alembic import op
import sqlalchemy as sa

"""add geospatial indexes

Revision ID: 68114fe044fb
Revises: 48b2ed7eba89
Create Date: 2024-12-07 13:12:14.219811

"""

# revision identifiers, used by Alembic.
revision = "68114fe044fb"
down_revision = "48b2ed7eba89"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_ride_geo_end_geo",
        "ride_geo",
        ["end_geo"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        "idx_ride_geo_start_geo",
        "ride_geo",
        ["start_geo"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        "idx_ride_tracks_gps_track",
        "ride_tracks",
        ["gps_track"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_foreign_key(None, "ride_tracks", "rides", ["ride_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "ride_tracks", type_="foreignkey")
    op.drop_index(
        "idx_ride_tracks_gps_track", table_name="ride_tracks", postgresql_using="gist"
    )
    op.drop_index(
        "idx_ride_geo_start_geo", table_name="ride_geo", postgresql_using="gist"
    )
    op.drop_index(
        "idx_ride_geo_end_geo", table_name="ride_geo", postgresql_using="gist"
    )
    # ### end Alembic commands ###
